config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  get 'products/:id' => 'products#show', as: :product

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy', as: :sign_out

end

app/models/product.rb
class Product < ActiveRecord::Base
  def price_in_dollars
    self.price_in_cents.to_i / 100.00
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

  def authenticate_user!
    if @current_user.blank?
      redirect_to sign_in_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:email]
    password = params[:password]

    user = User.find_by email: email

    if user.present? && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Famazon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <% if @current_user %>
      <div class="sign_in_notice">
        "You are signed in!"
      </div>
      <%= link_to "Sign Out", sign_out_path, method: :delete %>
  <% else %>
    <%= link_to "Sign In", sign_in_path %>
  <% end %>
</nav>
  <%= yield %>

</body>
</html>

app/views/products/index.html.erb
<%= @products.each do |product| %>
  <div class="product_container">
    <div class="product_name">
      <%= link_to product.name, product_path(id: product.id) %>
    </div>
    <div class="product_description">
      <%= product.description %>
    </div>
    <div class="product_price">
      Price: <%= product.price_in_dollars %>
    </div>
    <img src="<%= product.image_url %>" height="80"></img>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="product_on_page">
  <%= @product.name %>
  <%= @product.description %>
  <%= @product.price_in_dollars %>
  <%= @product.quantity %>
</div>